import {
  Database,
  BarChart3,
  LineChart,
  Pill,
  Truck,
  ShoppingBag,
  Megaphone,
  Landmark,
  Compass,
} from 'lucide-react'

export const SUITES = [
  {
    id: 'data-engineering',
    number: '01',
    name: 'Enterprise Data Foundation Suite',
    type: 'foundation',
    icon: Database,
    imageUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=1000&q=80',
    tagline: 'Connect Siloed Enterprise Data & Automate Real-Time Reporting',
    executiveSummary:
      'Connects multi-cloud databases, legacy software, and business APIs into a self-healing automated data pipeline',
    businessImpact: '85% less manual pipeline troubleshooting (IBM)',
    outcomes: [
      'Zero manual effort required to compile executive reports',
      'Single-source-of-truth metrics across all departments',
      'Self-healing automation that prevents system downtime',
    ],
    subDomains: ['Automated Ingestion', 'Smart Data Mapping', 'Self-Healing Pipelines'],
    accelerators: [
      { name: 'Data Ingestion Nexus', type: 'Data Connector', desc: 'Connects multi-cloud databases into a real-time data stream effortlessly' },
      { name: 'ETL Nexus', type: 'Pipeline Automation', desc: 'Automates extraction and database loading without manual intervention' },
      { name: 'SQL Forge', type: 'Plain English Querying', desc: 'Translates plain English questions into optimized ANSI SQL queries instantly' },
      { name: 'Pipeline Architect', type: 'DAG Builder', desc: 'Visually constructs dynamic data processing pipelines with built-in error handling' },
      { name: 'Recovery Phoenix', type: 'Auto-Healing Agent', desc: 'Detects broken feeds and retries failed pipeline steps with zero downtime' },
    ],
  },
  {
    id: 'data-quality',
    number: '02',
    name: 'Data Trust & Governance Suite',
    type: 'foundation',
    icon: BarChart3,
    imageUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1000&q=80',
    tagline: 'Guaranteed Single Source of Truth for Boardroom Decisions',
    executiveSummary:
      'Cleans datasets, eliminates duplicate records, and enforces data governance compliance across all company systems',
    businessImpact: '70% reduction in data entry requirements (IBM & Deloitte)',
    outcomes: [
      'Creates 360° Master Golden Records for clients and suppliers',
      'Prevents costly shipping, billing, and regulatory filing errors',
      'Ensures full data audit readiness for executive board review',
    ],
    subDomains: ['Golden Record MDM', 'Automated Cleansing', 'Compliance Guardrails'],
    accelerators: [
      { name: 'Golden Record Prime', type: 'Master Profile Creator', desc: 'Consolidates duplicate customer records into a single accurate master profile' },
      { name: 'Data Cleansing Forge', type: 'Anomaly Cleaner', desc: 'Strips corrupt formatting and invalid values automatically upon entry' },
      { name: 'Data Validation Sentinel', type: 'Error Preventer', desc: 'Validates records against strict business rules before client billing occurs' },
      { name: 'Address Validation Atlas', type: 'Address Verifier', desc: 'Verifies and normalizes global postal and shipping addresses instantly' },
    ],
  },
  {
    id: 'data-science',
    number: '03',
    name: 'Rapid Analytics Suite',
    type: 'foundation',
    icon: LineChart,
    imageUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1000&q=80',
    tagline: 'Real-Time Dashboards, Predictive Models & Executive Reporting',
    executiveSummary:
      'Converts raw enterprise data into real-time dashboards, predictive models, and executive reporting — without manual analyst intervention',
    businessImpact: '63% of enterprise use cases need data processed in minutes (IDC via IBM)',
    outcomes: [
      'Turns raw enterprise data into live executive dashboards automatically',
      'Surfaces predictive trends and anomalies before they impact the business',
      'Removes manual analyst effort from recurring boardroom reporting',
    ],
    subDomains: ['Real-Time Dashboards', 'Predictive Modeling', 'Executive Reporting'],
    accelerators: [
      { name: 'DashForge', type: 'Live Dashboard Builder', desc: 'Turns raw enterprise data into real-time executive dashboards automatically' },
      { name: 'ForecastIQ', type: 'Predictive Modeling Engine', desc: 'Builds predictive models from historical data to flag trends before they happen' },
      { name: 'ReportPilot', type: 'Executive Report Generator', desc: 'Compiles boardroom-ready reports and narrative insights without analyst input' },
      { name: 'InsightScout', type: 'Anomaly Detector', desc: 'Continuously scans live metrics to surface anomalies before they affect the business' },
    ],
  },
  {
    id: 'retail-ecommerce',
    number: '01',
    name: 'Sales & Customer Growth Suite',
    type: 'industry',
    icon: ShoppingBag,
    imageUrl: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=1000&q=80',
    tagline: 'Accelerate Sales Close Rates & Customer Lifetime Value',
    executiveSummary:
      'Lead scoring, proposal drafting, dynamic product pricing, and customer churn prediction',
    businessImpact: '30% increase in RFP win rate with AI-generated proposals (McKinsey)',
    outcomes: [
      'Tells sales teams exactly which prospective deals will close first',
      'Generates custom enterprise proposals in under 1 hour instead of 4 days',
      'Flags at-risk customer accounts early so managers can step in to save revenue',
    ],
    subDomains: ['Sales Pipeline Execution', 'Proposal Automation', 'Customer Churn Prevention'],
    accelerators: [
      { name: 'DealIQ', type: 'Deal Close Predictor', desc: 'Analyzes buyer interactions to highlight deals closest to signing' },
      { name: 'ProposalForge', type: 'Instant Proposal Writer', desc: 'Assembles custom RFP responses and client proposals in minutes' },
      { name: 'RetainAI', type: 'Customer Churn Guard', desc: 'Identifies unhappy customer accounts early to protect recurring revenue' },
    ],
  },
  {
    id: 'digital-marketing',
    number: '02',
    name: 'Digital Growth & Brand Protection Suite',
    type: 'industry',
    icon: Megaphone,
    imageUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1000&q=80',
    tagline: 'Multiply Content Volume 5x While Safeguarding Brand Compliance',
    executiveSummary:
      'Campaign strategy automation, AI content creation, and real-time brand compliance checking across all channels',
    businessImpact: '5-15% increase in marketing productivity from gen AI (McKinsey)',
    outcomes: [
      'Multiplies marketing content creation volume by 5x across all channels',
      'Prevents off-brand messaging, grammar mistakes, and legal compliance errors',
      'Improves organic acquisition via AI-optimized search engine structures',
    ],
    subDomains: ['Multi-Channel Strategy', 'SEO Optimization', 'Brand Policy Guard'],
    accelerators: [
      { name: 'CampaignForge', type: 'Omnichannel Launch Planner', desc: 'Drafts end-to-end launch strategies, ad variants, and messaging' },
      { name: 'BrandShield', type: 'Brand Compliance Checker', desc: 'Audits all marketing copy before publication to prevent brand mistakes' },
      { name: 'WordSmith', type: 'Brand-Voice Copywriter', desc: 'Writes long-form blogs, whitepapers, and articles matching your company tone' },
    ],
  },
  {
    id: 'supply-chain',
    number: '03',
    name: 'Supply Chain & Procurement Suite',
    type: 'industry',
    icon: Truck,
    imageUrl: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=1000&q=80',
    tagline: 'Predictive Stock Planning & Automated Vendor Negotiations',
    executiveSummary:
      'Inventory stockout prediction, vendor contract auditing and fuel-efficient logistics route calculation',
    businessImpact: '12-20% procurement savings identified through AI agents (McKinsey)',
    outcomes: [
      'Prevents inventory stockouts that result in lost customer sales',
      'Scans supplier contracts automatically to highlight price inflation',
      'Calculates fuel-efficient delivery routes to lower fleet logistics expenses',
    ],
    subDomains: ['Vendor Negotiations', 'Predictive Replenishment', 'Logistics Route Optimization'],
    accelerators: [
      { name: 'SourceAI', type: 'Vendor Savings Finder', desc: 'Audits supplier agreements to spot hidden price increases and savings' },
      { name: 'DemandPilot', type: 'Stock Shortage Predictor', desc: 'Forecasts regional customer purchasing surges so warehouses stay stocked' },
      { name: 'RouteIQ', type: 'Fleet Route Optimizer', desc: 'Finds the fastest delivery paths to lower fuel and driver expenses' },
    ],
  },
  {
    id: 'transport-logistics',
    number: '04',
    name: 'Logistics & Fleet Operations Suite',
    type: 'industry',
    icon: Compass,
    imageUrl: 'https://images.unsplash.com/photo-1519003722824-194d4455a60c?auto=format&fit=crop&w=1000&q=80',
    tagline: 'Predictive Maintenance & Dynamic Delivery Optimization',
    executiveSummary:
      'Vehicle telematics monitoring, optimal delivery route calculation, and live customer delivery tracking',
    businessImpact: '26% increase in fleet technician productivity (IBM)',
    outcomes: [
      'Alerts fleet mechanics to repair needs before costly breakdowns occur',
      'Lowers fleet fuel expenditure with traffic-aware route optimization',
      'Keeps clients happy with accurate, real-time estimated arrival updates',
    ],
    subDomains: ['Fleet Breakdown Prevention', 'Route Fuel Optimization', 'Live Customer Tracking'],
    accelerators: [
      { name: 'FleetPulse', type: 'Predictive Fleet Monitor', desc: 'Analyzes engine telemetry to alert mechanics before breakdowns happen' },
      { name: 'RouteIQ', type: 'Smart Route Dispatcher', desc: 'Calculates the fastest, fuel-efficient delivery paths considering live traffic' },
      { name: 'CargoTrack', type: 'Customer Delivery Tracker', desc: 'Recalculates estimated arrival times and notifies customers automatically' },
    ],
  },
  {
    id: 'healthcare-pharma',
    number: '05',
    name: 'Pharmaceutical R&D Suite',
    type: 'industry',
    icon: Pill,
    imageUrl: 'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?auto=format&fit=crop&w=1000&q=80',
    tagline: 'Speed Up Clinical Research & Automate Regulatory Filings',
    executiveSummary:
      'Patient matching for clinical trials, medical research summarisation and FDA/HIPAA regulatory compliance checks',
    businessImpact: '50-60% reduction in clinical data verification time (Deloitte)',
    outcomes: [
      'Shortens clinical candidate matching from 6 weeks to 3 days',
      'Automates regulatory dossier reviews for FDA/EMA submissions',
      'Monitors real-world patient safety notes continuously to flag drug side-effects',
    ],
    subDomains: ['Clinical Trial Acceleration', 'Regulatory Auditing', 'Patient Safety'],
    accelerators: [
      { name: 'TrialIQ', type: 'Trial Cohort Matcher', desc: 'Parses complex clinical trial protocols to identify matching patient pools instantly' },
      { name: 'MedReader', type: 'Research Synthesizer', desc: 'Scans thousands of medical journals to summarize research insights in minutes' },
      { name: 'ComplianceRx', type: 'Regulatory Auditor', desc: 'Audits submission documents against FDA and HIPAA guidelines automatically' },
    ],
  },
  {
    id: 'bfsi',
    number: '06',
    name: 'Financial & Accounting Suite',
    type: 'industry',
    icon: Landmark,
    imageUrl: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?auto=format&fit=crop&w=1000&q=80',
    tagline: 'Automate Underwriting, Fraud Prevention & Financial Operations',
    executiveSummary:
      'Insurance underwriting, invoice processing, expense auditing, risk scoring and real-time fraud detection',
    businessImpact: '50-75% reduction in invoice processing time (Deloitte)',
    outcomes: [
      'Automates accounts payable processing to eliminate manual data entry errors',
      'Stops fraudulent transaction charges instantly in real-time streams',
      'Speeds up business loan approvals safely while maintaining zero audit violations',
    ],
    subDomains: ['Financial Operations', 'Loan Underwriting Risk', 'Real-Time Fraud Shield'],
    accelerators: [
      { name: 'InvoiceFlow', type: 'Automated Invoice Processor', desc: 'Extracts invoice details, matches purchase orders, and queues payment' },
      { name: 'FraudShield', type: 'Real-Time Fraud Blocker', desc: 'Monitors transaction feeds continuously to stop unauthorized charges' },
      { name: 'CreditIQ', type: 'Loan Approval Assistant', desc: 'Evaluates applicant creditworthiness quickly using alternative risk signals' },
    ],
  },
]
