/**
 * Travel, Transport & Logistics page content. Same template contract as
 * `pharma.js` — copy is verbatim from the original capture, typos included.
 */
export const TRAVEL = {
  // this page's band leads run the muted grey, not the purple
  leadTone: "muted",
  // travel alternates its surfaces differently to the other industry pages
  tones: { trust: "light", problems: "tinted" },
  hero: {
    line1: "Zero-Latency Orchestration for",
    line2: "Travel, Transport & Logistics",
  },

  trust: {
    titleTop: "From Operational Complexity to",
    // The original sets a non-breaking hyphen (U+2011) in "Data‑Driven".
    titleAccent: "Data‑Driven Precision",
    subtitle:
      "In a real-time, low-margin industry, unified data enables predictive operations, resilient networks, and sustained efficiency gains",
    stats: [
      {
        value: "35%",
        icon: "clock",
        body: "Aircraft turnaround time reduction delivered for a major UK airport via real-time ground-ops visibility",
      },
      {
        value: "$14T",
        icon: "globe",
        body: "Global logistics market value, where data intelligence is the primary competitive differentiator",
      },
      {
        value: "50%",
        icon: "doc",
        body: "Faster technician data entry achieved by replacing paper-based tarmac logging with real-time edge PWA",
      },
      {
        value: "2.5X",
        icon: "gear",
        body: "More fuel waste generated by fleets operating without AI-driven route and scheduling optimisation",
      },
    ],
  },

  problems: {
    titleTop: "Information Black Holes -",
    titleAccent: "the invisible cost of fragmented operations",
    subtitle:
      "Flight management systems don’t talk to ground handling, maintenance platforms don’t feed scheduling, fleet telematics don’t integrate with route optimisation – leading to costly delays and failures. Ignitho connects what you already have, surfacing intelligence buried in your operational data",
    // The card titles on the original are travel-specific but every card body is
    // still the pharma placeholder text, in both the mobile and desktop copies.
    // Kept verbatim rather than rewritten.
    items: [
      {
        title: "Information black holes in ground operations",
        body: "Lab systems, EHR platforms, clinical trial databases, and imaging systems operate in isolation",
      },
      {
        title: "No real-time visibility across fleet and route performance",
        body: "Manual scheduling leads to over-bookings, no-shows, and wasted clinician time",
      },
      {
        title: "Maintenance scheduling driven by manual processes",
        body: "GxP, HIPAA, and GDPR slow collaboration and delay insight sharing across clinical teams",
      },
      {
        title: "Legacy booking systems at capacity limits",
        body: "Legacy systems delay integration of trial data with real-world evidence",
      },
    ],
  },

  solutions: {
    // the original hard-breaks before the accent line on this page
    stacked: true,
    titleTop: "From ground to air -",
    titleAccent: "operations intelligence at every node",
    subtitle:
      "Every solution is drawn from Ignitho’s Zero Latency Orchestration framework building on TroyAvi’s travel domain expertise, integrating within existing tech stacks, not replacing them",
    flagship: {
      label: "FLAGSHIP SOLUTION",
      title: "Route & Fleet Optimization",
      body: "AI-driven models maximising asset utilisation and minimising fuel and operational costs. Real-time route optimisation accounting for demand signals, maintenance schedules, and regulatory requirements, improving on-time performance without adding new infrastructure",
    },
    items: [
      {
        title: "Real-Time Operational Analytics & Ground-to-Air Visibility",
        body: "Single operational intelligence layer connecting ground handling, maintenance, crew, and scheduling systems into one real-time view, eliminating information black holes causing TAT delays and reporting lags",
      },
      {
        title: "Predictive Maintenance & Crew Scheduling",
        body: "AI-led maintenance and crew scheduling models plugging directly into legacy tech stacks, predicting maintenance requirements before they become unplanned events and optimising crew allocation",
      },
      {
        title: "Freight & Supply Chain Visibility",
        body: "End-to-end freight intelligence connecting supplier, carrier, warehouse, and last-mile data into a governed visibility layer with proactive operational insights",
      },
    ],
  },

  approach: {
    // the original's card row is 1280 wide here (4 cards + 3 x 20 gaps)
    rowMax: 1280,
    titleTop: "From Data Fragmentation to Operational Intelligence -",
    titleAccent: "in rapid sprints",
    subtitle:
      "Slow data projects mean missed seasons, compounding TAT penalties, and operational costs that accumulate daily. Our 7-to-30-day sprint model gets working intelligence into your ops, fleet, and planning teams within weeks",
    steps: [
      {
        title: "7-Day Operations Data Triage",
        body: "Map your operational systems – GDS, flight management, MRO, crew scheduling, and fleet telematics. Identify where information black holes are costing the most",
      },
      {
        title: "Unified Data Foundation & Integration Layer",
        body: "Build the governed integration layer connecting your operational systems without replacing them. Real-time event pipelines feeding route optimisation, fleet analytics, and scheduling intelligence",
      },
      {
        title: "Iterative Delivery - 7 to 30-Day Sprints",
        titleLines: ["Iterative Delivery -","7 to 30-Day Sprints"],
        body: "Specialist POD teams deploy in short visible cycles. Each sprint closes with a working ops tool – a live fleet dashboard, predictive maintenance model, or route optimisation engine",
      },
      {
        title: "Stabilize, Enable & Scale",
        titleLines: ["Stabilize, Enable &","Scale"],
        body: "Production hardening, runbook documentation, and team enablement. Your operations and planning teams run every model and dashboard independently",
      },
    ],
  },

  why: {
    title: "Why Ignitho",
    subtitle:
      "Most data vendors understand technology. Very few understand the operational constraints of a live airport or a 24/7 freight network. Our TroyAvi partnership makes every technical solution operationally viable from Day One",
    image: {
      src: "/images/why-ignitho.webp",
      alt: "Ignitho consultants working with a travel, transport and logistics client team",
    },
    left: [
      {
        // Verbatim from the desktop capture, which still carries the media
        // page's card here. The mobile-only copy of this slot instead reads
        // "Non-disruptive by design" / "We integrate within your existing GDS,
        // flight management, and logistics platforms…".
        title: "Platform-agnostic editorial integration",
        body: "We build on top of your existing CMS, analytics, and ad platforms. Zero vendor lock-in. Zero platform replacement. Immediate ROI without disruption to live editorial operations",
      },
      {
        title: "Day-1 productive senior practitioners",
        body: "Senior data engineers and data scientists who integrate into your operation from week one. No onboarding theatre. They pick up your backlog and start delivering",
      },
    ],
    right: [
      {
        title: "Aviation domain expertise via TroyAvi",
        body: "Our TroyAvi partnership brings hands-on aviation domain expertise - airline strategy, airport operations, MRO, and air cargo - into every technical engagement",
      },
      {
        title: "Frugal innovation for operations",
        body: "Maximum intelligence from your existing operational technology investments. We make your existing GDS, telematics, and MRO platforms work harder, not replace them",
      },
    ],
  },
};
